"$schema" = 'https://starship.rs/config-schema.json'

format="""
$directory\
$git_branch\
$git_status\
$character
"""

right_format = """
$docker_context\
$lua\
$python\
$rust\
$terraform\
$nodejs\
$cmd_duration\
$jobs\
$memory_usage\
$aws\
$gcloud
"""

# format='$character'

palette="catppuccin_macchiato"



[character]
success_symbol = "[❯](bold mauve)"
error_symbol = "[❯](bold red)"

[memory_usage]
threshold = 50
symbol = " "
format = "$symbol[$ram( | $swap)]($style) "
style = "pink bold"


[directory]
home_symbol = "~"
style = "blue bold"

[nodejs]
format = "[$symbol($version )]($style)"

[git_branch]
symbol = ""
style = "overlay0"
format = "[$symbol$branch(:$remote_branch)]($style)"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "subtext1"
modified = "*"
staged = "+"
ahead = "⇡"
behind = "⇣"
untracked = ""
stashed = ""

[aws]
format = "[$symbol($profile )(\\($region\\) )(\\[$duration\\] )]($style)"
symbol = " "
style = "bold yellow"

[gcloud]
format = "[$symbol$active(\\($region\\))]($style) "
disabled = false
symbol = " "

[python]
symbol = " "


[palettes.catppuccin_macchiato]
rosewater = "#F4DBD6"
flamingo = "#F0C6C6"
pink = "#F5BDE6"
mauve = "#C6A0F6"
red = "#ED8796"
maroon = "#EE99A0"
peach = "#F5A97F"
yellow = "#EED49F"
green = "#A6DA95"
teal = "#8BD5CA"
sky = "#91D7E3"
sapphire = "#7DC4E4"
blue = "#8AADF4"
lavender = "#B7BDF8"
text = "#CAD3F5"
subtext1 = "#B8C0E0"
subtext2 = "#A5ADCB"
overlay2 = "#939AB7"
overlay1 = "#8087A2"
overlay0 = "#6E738D"
surface2 = "#5B6078"
surface1 = "#494D64"
surface0 = "#363A4F"
base = "#24273A"
mantle = "#1E2030"
crust = "#181926"
